import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import CandidateMenu from "../components/candidates/CandidateMenu";
import FeaturedJobs from "../components/candidates/FeaturedJobs";
import RecentActivies from "../components/candidates/RecentActivies";
import Footer from "../components/footer/Footer";
import LayoutHeader from "../components/header/LayoutHeader";

function CandidateLayout({ children }) {
  const currentPath = useRouter().pathname;
  return (
    <>
      <Head>
        <title>JOBES- Job Portal NextJs Template</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="/assets/images/sm-logo.svg"
          type="image/gif"
          sizes="20x20"
        />
      </Head>
      <LayoutHeader />
      <div className="dashboard-area pt-120 mb-120">
        <div className="container">
          <div
            className={
              currentPath === "/candidates-dashboard/view-resume"
                ? "row justify-content-center g-lg-4 gy-5 mb-90"
                : "row g-lg-4 gy-5 mb-90"
            }
          >
            {currentPath === "/candidates-dashboard/view-resume" ? (
              ""
            ) : (
              <div className="col-lg-3">
                <div className="dashboard-sidebar">
                  <CandidateMenu />
                  <RecentActivies />
                </div>
              </div>
            )}
            {children}
          </div>
          {currentPath === "/candidates-dashboard/dashboard" ? (
            <FeaturedJobs />
          ) : (
            ""
          )}
        </div>
      </div>

      <Footer />
    </>
  );
}

export default CandidateLayout;
