import Head from "next/head";
import React from "react";
import CompanyDashbordMenu from "../components/company/CompanyDashbordMenu";
import Footer from "../components/footer/Footer";
import LayoutHeader from "../components/header/LayoutHeader";

function CompanyDashbordLayout({ children }) {
  return (
    <>
      <Head>
        <title>JOBES- Job Portal NextJs Template</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="/assets/images/sm-logo.svg"
          type="image/gif"
          sizes="20x20"
        />
      </Head>
      <LayoutHeader />
      <div className="dashboard-area company-dashboard pt-120 mb-120">
        <div className="container">
          <div className="row g-lg-4">
            <CompanyDashbordMenu />
            {children}
          </div>
        </div>
      </div>

      <Footer />
    </>
  );
}

export default CompanyDashbordLayout;
