import { useRouter } from "next/router";
import { useEffect } from "react";
import Head from "next/head";
import Home2Article from "../components/article/Home2Article";
import Banner2 from "../components/banner/Banner2";
import Home2Category from "../components/category/Home2Category";
import Counter2 from "../components/counter/counter2";
import Home3Feature from "../components/feature/Home3Feature";
import Home2Feedback from "../components/feedback/Home2Feature";
import Footer from "../components/footer/Footer";
import Header2 from "../components/header/Header2";
import Home2LatesJob from "../components/latest-job/Home2LatesJob";
import Home2TopRecruiters from "../components/top-recruiters/Home2TopRecruiters";
import Home2TrustedCompany from "../components/trusted-company/Home2TrustedCompany";
import Home2WorkProcess from "../components/work-process/Home2WorkProcess";

function Home() {
  const currentPage = useRouter().pathname;
  useEffect(() => {
    if (currentPage === "/") {
      document.body.className = "bg-wight";
    }
    return () => {
      document.body.className = ""; // Reset on unmount
    };
  }, [currentPage]);
  return (
    <>
        <Head>
        <title>JOBES- Job Portal NextJs Templat</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />        
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        />
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="assets/images/sm-logo.svg"
          type="image/gif"
          sizes="20x20"
        />
      </Head>
      <Header2 />
      <Banner2 />
      <Counter2 />
      <Home2Category />
      <Home2LatesJob />
      <Home2WorkProcess />
      <Home3Feature />
      <Home2TopRecruiters />
      <Home2Feedback />
      <Home2TrustedCompany />
      <Home2Article />
      <Footer />
    </>
  );
}

export default Home;
